### ISSUE TITLE
Shut down itself

### ISSUE THREAD

**Issue by ckwcfm** [abesnier/docker-guacamole#21]
it shut down itself after few hours it start.

**Comment by abesnier** [comment]
That's not an issue I've ever encountered.

Can you confirm the tag you are using, the architecture, and your command line/docker-compose?

**Comment by ckwcfm** [comment]
thank you for your reply, I am using this image: guacamole:1.5.2-alpine-pg15
and here is my docker-compose.yml. I am using in a docker swarm environment 

```
version: "3"
services:
  guacamole:
    image: abesnier/guacamole:1.5.2-alpine-pg15
    networks:
      - tailscale
      - proxy
    user: root
    volumes:
      - gua-config:/config
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.manager == ironman

networks:
  tailscale:
    external: true
  proxy:
    external: true

volumes:
  gua-config:
```
