### ISSUE TITLE
SAML issue

### ISSUE THREAD

**Issue by Reneftec** [abesnier/docker-guacamole#30]
Evening,

I'm trying to connect to Azure AD using SAML. I've set everything up but am getting the following error

```
20:13:58.532 [http-nio-8080-exec-5] WARN  o.a.g.e.AuthenticationProviderFacade - The "saml" authentication provider has encountered an internal error which will halt the authentication process. If this is unexpected or you are the developer of this authentication provider, you may wish to enable debug-level logging. If this is expected and you wish to ignore such failures in the future, please set "skip-if-unavailable: saml" within your guacamole.properties.
20:13:58.542 [http-nio-8080-exec-5] ERROR o.a.g.rest.RESTExceptionMapper - An internal error occurred, but did not contain an error message. Enable debug-level logging for details.
```

I'm not sure where to find further logs or if I'm missing something obvious. A copy of my compose file is below

```
version: "3"
services:
  guacamole:
    image: abesnier/guacamole
    container_name: guacamole
    volumes:
      - postgres:/config
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/London
      - EXTENSIONS=auth-sso-saml
      - EXTENSION_PRIORITY=*, saml
      - SAML_IDP_METADATA_URL=https://login.microsoftonline.com/xxxxxxxxxxxxxxxxxxx/federationmetadata/2007-06/federationmetadata.xml?appid=xxxxxxxxxxxxxxxxxxxx
      - SAML_IDP_URL=https://login.microsoftonline.com/xxxxxxxxxxxxxxxxxxxxx/saml2
      - SAML_ENTITY_ID=https://you.me.them
      - SAML_CALLBACK_URL=https://you.me.them

      - GUACD_LOG_LEVEL=debug
      - SAML_STRICT=false
      - SAML_DEBUG=true
volumes:
  postgres:
    driver: local
```
